server:
  port: 8100
  security:
    ignore:
      urls: /actuator/**,/auth/oauth/token
spring:
  application:
    name: TRANSACTION-GATEWAY-API
  main:
    allow-bean-definition-overriding: true
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: oauth-server-route
          uri: lb://transaction-auth-server
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
            - name: Hystrix
              args:
                name: fallbackcmd
                fallbackUri: forward:/defaultFallback
            - name: Retry
              args:
                retries: 1
                statuses: BAD_GATEWAY,INTERNAL_SERVER_ERROR,SERVICE_UNAVAILABLE
                methods: GET,POST
        - id: user-server-route
          uri: lb://transaction-user-server
          predicates:
            - Path=/sys/**
          filters:
            - StripPrefix=1
            - name: Hystrix
              args:
                name: fallbackcmd
                fallbackUri: forward:/defaultFallback
  security:
    oauth2:
      resourceserver:
        jwt:
          #jwk-set-uri: http://localhost:8003/rsa/publicKey 暂无高可用方案，只能采用本地文件
          public-key-location: classpath:publicKeyLocation.txt

# Eureka 注册中心
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka/

# 超时配置
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            # 全局熔断器3s超时
            timeoutInMilliseconds: 5000
